sudo: required
service:
  - docker

before_install:
  - docker build -t ibn1029/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ibn1029/docker-react npm run test

deploy:
  edge: ture
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env-3"
  bucket_name: "elasticbeanstalk-us-east-1-690349992266"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
